version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ".:/var/www/html/:delegated"
      - "~/.composer/docker-cache/:/root/.composer:cached"
    working_dir: "/var/www/html/"
