name: php-suite-api Build

on: push

env:
  PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    name: Tests & Deploy 🚦🚢
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup and start container
        run: make all
      - name: Run tests
        run: make test
      - name: Release package
        run: composer publish emartech ${PACKAGIST_TOKEN}
      - name: Slack notification
        uses: 8398a7/action-slack@a189acbf0b7ea434558662ae25a0de71df69a435
        with:
          status: ${{ job.status }}
          fields: repo,message,author,job,ref
          job_name: Tests & Deploy 🚦🚢
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
